repos:
  - repo: https://github.com/duolingo/pre-commit-hooks.git
    rev: 1.11.1
    hooks:
      - id: duolingo
  - repo: local
    hooks:
      - id: copyright
        name: Copyright
        entry: |
          bash -c 'for f in $@;do if ! grep -q © "${f}";then sed -i "1s@^@// © Art Chaidarun\n\n@" "${f}";fi;done' -
        language: system
        files: \.kt$
